#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 04, 2022 06:46:07 PM +0300  platform: Windows NT

import sys
import tkinter as tk
import threading
import tkinter.ttk as ttk
from tkinter.constants import *


class Toplevel1:
    def __init__(self, mainScreen, subgroupScreen):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        self.frame = mainScreen.Frame3
        self.top = mainScreen.top
        self.sock = mainScreen.sock
        self.groupName = subgroupScreen.groupName
        self.subgroupHeight = subgroupScreen.subgroupHeight
        self.subgroupScreen = subgroupScreen
        self.mainScreen = mainScreen

        self.Frame7 = tk.Frame(self.frame)
        self.Frame7.place(relx=0.254, rely=0.25, relheight=0.5, relwidth=0.5)
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#ffffff")
        self.Frame7.configure(highlightbackground="#d9d9d9")
        self.Frame7.configure(highlightcolor="black")

        self.Label16 = tk.Label(self.Frame7)
        self.Label16.place(relx=0.05, rely=0.059, height=49, width=575)
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(anchor='w')
        self.Label16.configure(background="#ffffff")
        self.Label16.configure(compound='left')
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(font="-family {Segoe UI} -size 22 -weight bold")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''Create Channel''')

        self.Label17 = tk.Label(self.Frame7)
        self.Label17.place(relx=0.05, rely=0.149, height=22, width=575)
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(anchor='w')
        self.Label17.configure(background="#ffffff")
        self.Label17.configure(compound='left')
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(font="-family {Segoe UI} -size 10")
        self.Label17.configure(foreground="#777c84")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''in Text Channels''')

        self.Label18 = tk.Label(self.Frame7)
        self.Label18.place(relx=0.051, rely=0.501, height=25, width=120)
        self.Label18.configure(activebackground="#4752c4")
        self.Label18.configure(activeforeground="white")
        self.Label18.configure(activeforeground="#ffffff")
        self.Label18.configure(anchor='nw')
        self.Label18.configure(background="#ffffff")
        self.Label18.configure(compound='left')
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label18.configure(foreground="#515862")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''Channel name''')

        self.Entry3 = tk.Entry(self.Frame7)
        self.Entry3.place(relx=0.051, rely=0.57, height=41, relwidth=0.899)
        self.Entry3.configure(background="#e3e5e8")
        self.Entry3.configure(borderwidth="0")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="blue")
        self.Entry3.configure(selectforeground="white")

        self.Frame8 = tk.Frame(self.Frame7)
        self.Frame8.place(relx=0.0, rely=0.819, relheight=0.191, relwidth=1.0)
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#f2f3f5")
        self.Frame8.configure(highlightbackground="#d9d9d9")
        self.Frame8.configure(highlightcolor="black")

        self.Button4 = tk.Button(self.Frame8)
        self.Button4.place(relx=0.802, rely=0.309, height=44, width=90)
        self.Button4.configure(activebackground="#4752c4")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(activeforeground="#ffffff")
        self.Button4.configure(background="#5865f2")
        self.Button4.configure(borderwidth="0")
        self.Button4.configure(compound='left')
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Button4.configure(foreground="#ffffff")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''create''')
        self.Button4.bind('<Button-1>', self.create)

        self.Button6 = tk.Button(self.Frame7)
        self.Button6.place(relx=0.919, rely=0.029, height=28, width=27)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ffffff")
        self.Button6.configure(borderwidth="0")
        self.Button6.configure(compound='left')
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        photo_location = "Images/exit.png"
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Button6.configure(image=_img2)
        self.Button6.configure(pady="0")
        self.Button6.bind('<Button-1>', self.exit)

    def exit(self, event):
        self.Frame7.destroy()

    def create(self, event):
        subgroupName = self.Entry3.get()

        threading.Thread(target=self.sock.createMessage, args=("ADD_SUBGROUP", self.groupName, subgroupName)).start()
        while self.sock.messageQueue.empty():
            self.refresh()
        clientMessage = self.sock.messageQueue.get()

        self.Entry3.delete(0, 'end')

        if clientMessage == "GTIT":
            self.createSubgroupButton(subgroupName)
            self.Frame7.destroy()

        elif clientMessage == "SUBGROUP_EXIST":
            self.Button4.configure(text='''Channel Exists''', background="red")
            self.top.after(1000, lambda: self.Button4.configure(text='''Create''', background="#5865f2"))

    def createSubgroupButton(self, subgroupName):
        Label6 = tk.Label(self.subgroupScreen.frame)
        Label6.place(relx=0.021, rely=self.subgroupHeight, height=24, width=19)
        Label6.configure(activebackground="#f9f9f9")
        Label6.configure(activeforeground="black")
        Label6.configure(background="#2f3035")
        Label6.configure(compound='left')
        Label6.configure(disabledforeground="#a3a3a3")
        Label6.configure(font="-family {Segoe UI} -size 20")
        Label6.configure(foreground="#6d6e73")
        Label6.configure(highlightbackground="#d9d9d9")
        Label6.configure(highlightcolor="black")
        Label6.configure(text='''#''')

        Button2 = tk.Button(self.subgroupScreen.frame)
        Button2.place(relx=0.1, rely=self.subgroupHeight, height=24, width=192)
        Button2.configure(activebackground="#42454e")
        Button2.configure(activeforeground="white")
        Button2.configure(activeforeground="#ffffff")
        Button2.configure(anchor='w')
        Button2.configure(background="#2f3035")
        Button2.configure(borderwidth="0")
        Button2.configure(compound='left')
        Button2.configure(disabledforeground="#a3a3a3")
        Button2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        Button2.configure(foreground="#6d6e73")
        Button2.configure(highlightbackground="#d9d9d9")
        Button2.configure(highlightcolor="black")
        Button2.configure(pady="0")
        Button2.configure(text=subgroupName)
        Button2.bind('<Button-1>', lambda event, g=subgroupName, b = Button2: self.subgroupScreen.getMessages(g, b))
        self.mainScreen.subgroupButtons.append(Button2)

    def refresh(self):
        self.top.update_idletasks()
        self.top.update()





